from flask_sqlalchemy import SQLAlchemy
from datetime import date
db = SQLAlchemy()

########################################################
#######                                          #######
#######           Step 1: Latest Tables          #######
#######                                          #######
########################################################
class Latest_Training(db.Model):
    CustomerId = db.Column(db.Integer, primary_key=True)
    Surname = db.Column(db.String(50), nullable=True)
    CreditScore = db.Column(db.Integer, nullable=True)
    Geography = db.Column(db.String(100), nullable=True)
    Gender = db.Column(db.String(10), nullable=True)
    Age = db.Column(db.Integer, nullable=True)
    Tenure = db.Column(db.Integer, nullable=True)
    Balance = db.Column(db.Float, nullable=True)
    NumOfProducts = db.Column(db.Integer, nullable=True)
    HasCrCard = db.Column(db.Boolean, nullable=True)
    IsActiveMember = db.Column(db.Boolean, nullable=True)
    EstimatedSalary = db.Column(db.Float, nullable=True)
    Exited = db.Column(db.Boolean, nullable=True)
    RecentSatisfactionScore = db.Column(db.Float, nullable=True)

class Latest_Scoring(db.Model):
    CustomerId = db.Column(db.Integer, primary_key=True)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(50), nullable=False)
    CreditScore = db.Column(db.Integer, nullable=False)
    Geography = db.Column(db.String(100), nullable=False)
    Gender = db.Column(db.String(10), nullable=False)
    Age = db.Column(db.Integer, nullable=False)
    Tenure = db.Column(db.Integer, nullable=False)
    Balance = db.Column(db.Float, nullable=False)
    NumOfProducts = db.Column(db.Integer, nullable=False)
    HasCrCard = db.Column(db.Boolean, nullable=False)
    IsActiveMember = db.Column(db.Boolean, nullable=False)
    EstimatedSalary = db.Column(db.Float, nullable=False)
    Exited = db.Column(db.Boolean, nullable=False)
    RecentSatisfactionScore = db.Column(db.Float, nullable=False)

class Latest_Scored(db.Model):
    CustomerId = db.Column(db.Integer, primary_key=True)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(100), nullable=False)
    Prediction = db.Column(db.Boolean, nullable=False)
    Churn_Probability = db.Column(db.Float, nullable=False)
    Top_1_Feat = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Score = db.Column(db.Float, nullable=False)
    Top_2_Feat = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Score = db.Column(db.Float, nullable=False)
    Top_3_Feat = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Score = db.Column(db.Float, nullable=False)
    Top_4_Feat = db.Column(db.String(100), nullable=False)
    Top_4_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_4_Feat_Score = db.Column(db.Float, nullable=False)
    Top_5_Feat = db.Column(db.String(100), nullable=False)
    Top_5_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_5_Feat_Score = db.Column(db.Float, nullable=False)

class Latest_Emails(db.Model):
    CustomerId = db.Column(db.Integer, primary_key=True)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(100), nullable=False)
    Prediction = db.Column(db.Boolean, nullable=False)
    Churn_Probability = db.Column(db.Float, nullable=False)
    LLM_Response = db.Column(db.String(4000), nullable=False)
    Top_1_Feat = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Score = db.Column(db.Float, nullable=False)
    Top_2_Feat = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Score = db.Column(db.Float, nullable=False)
    Top_3_Feat = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Score = db.Column(db.Float, nullable=False)

########################################################
#######                                          #######
#######         Step 2: Historical Tables        #######
#######                                          #######
########################################################
class Historical_Models(db.Model):
    meta_Id = db.Column(db.String(50), primary_key=True)
    meta_DateCreated = db.Column(db.Date, nullable=False)
    Accuracy = db.Column(db.Float, nullable=False)
    Precision = db.Column(db.Float, nullable=False)
    Recall = db.Column(db.Float, nullable=False)
    F1 = db.Column(db.Float, nullable=False)
    CountTrueNegative = db.Column(db.Integer, nullable=False)
    CountFalsePositive = db.Column(db.Integer, nullable=False)
    CountFalseNegative = db.Column(db.Integer, nullable=False)
    CountTruePositiove = db.Column(db.Integer, nullable=False)
    CountTrainingPositiveClass = db.Column(db.Integer, nullable=False)
    CountTrainingNegativeClass = db.Column(db.Integer, nullable=False)
    CountTestPositiveClass = db.Column(db.Integer, nullable=False)
    CountTestNegativeClass = db.Column(db.Integer, nullable=False)

class Historical_Training(db.Model):
    meta_Id = db.Column(db.String(50), primary_key=True)
    meta_DateCreated = db.Column(db.Date, nullable=False)
    CustomerId = db.Column(db.Integer, nullable=False)
    Surname = db.Column(db.String(50), nullable=True)
    CreditScore = db.Column(db.Integer, nullable=True)
    Geography = db.Column(db.String(100), nullable=True)
    Gender = db.Column(db.String(10), nullable=True)
    Age = db.Column(db.Integer, nullable=True)
    Tenure = db.Column(db.Integer, nullable=True)
    Balance = db.Column(db.Float, nullable=True)
    NumOfProducts = db.Column(db.Integer, nullable=True)
    HasCrCard = db.Column(db.Boolean, nullable=True)
    IsActiveMember = db.Column(db.Boolean, nullable=True)
    EstimatedSalary = db.Column(db.Float, nullable=True)
    Exited = db.Column(db.Boolean, nullable=True)
    RecentSatisfactionScore = db.Column(db.Float, nullable=True)

class Historical_Scoring(db.Model):
    meta_Id = db.Column(db.String(50), primary_key=True)
    meta_DateCreated = db.Column(db.Date, nullable=False)
    CustomerId = db.Column(db.Integer, nullable=False)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(50), nullable=False)
    CreditScore = db.Column(db.Integer, nullable=False)
    Geography = db.Column(db.String(100), nullable=False)
    Gender = db.Column(db.String(10), nullable=False)
    Age = db.Column(db.Integer, nullable=False)
    Tenure = db.Column(db.Integer, nullable=False)
    Balance = db.Column(db.Float, nullable=False)
    NumOfProducts = db.Column(db.Integer, nullable=False)
    HasCrCard = db.Column(db.Boolean, nullable=False)
    IsActiveMember = db.Column(db.Boolean, nullable=False)
    EstimatedSalary = db.Column(db.Float, nullable=False)
    Exited = db.Column(db.Boolean, nullable=False)
    RecentSatisfactionScore = db.Column(db.Float, nullable=False)

class Historical_Scored(db.Model):
    meta_Id = db.Column(db.String(50), primary_key=True)
    meta_DateCreated = db.Column(db.Date, nullable=False)
    CustomerId = db.Column(db.Integer, nullable=False)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(100), nullable=False)
    Prediction = db.Column(db.Boolean, nullable=False)
    Churn_Probability = db.Column(db.Float, nullable=False)
    Top_1_Feat = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Score = db.Column(db.Float, nullable=False)
    Top_2_Feat = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Score = db.Column(db.Float, nullable=False)
    Top_3_Feat = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Score = db.Column(db.Float, nullable=False)
    Top_4_Feat = db.Column(db.String(100), nullable=False)
    Top_4_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_4_Feat_Score = db.Column(db.Float, nullable=False)
    Top_5_Feat = db.Column(db.String(100), nullable=False)
    Top_5_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_5_Feat_Score = db.Column(db.Float, nullable=False)

class Historical_Emails(db.Model):
    meta_Id = db.Column(db.String(50), primary_key=True)
    meta_DateCreated = db.Column(db.Date, nullable=False)
    CustomerId = db.Column(db.Integer, nullable=False)
    Surname = db.Column(db.String(50), nullable=False)
    Email = db.Column(db.String(100), nullable=False)
    Prediction = db.Column(db.Boolean, nullable=False)
    Churn_Probability = db.Column(db.Float, nullable=False)
    LLM_Response = db.Column(db.String(4000), nullable=False)
    Top_1_Feat = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_1_Feat_Score = db.Column(db.Float, nullable=False)
    Top_2_Feat = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_2_Feat_Score = db.Column(db.Float, nullable=False)
    Top_3_Feat = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Value = db.Column(db.String(100), nullable=False)
    Top_3_Feat_Score = db.Column(db.Float, nullable=False)